defaults:
- visualization: eval
num_workers: 0
batch_size: 1
cuda: 0
weight_name: latest
enable_cudnn: true
checkpoint_dir: /home/ubuntu/binbin/OutdoorPanopticSeg_V2/outputs/tree_mix
model_name: PointGroup-PAPER
precompute_multi_scale: true
enable_dropout: false
voting_runs: 1
data:
  fold:
#  - /home/ubuntu/binbin/OutdoorPanopticSeg_V2/data_test/wythan/map/wythan_woods_all_trees_ground.ply
  - /home/ubuntu/binbin/OutdoorPanopticSeg_V2/data_test/todolist_2/17662.ply

tracker_options:
  full_res: true
  make_submission: true
  ply_output: maciej_eval.ply
hydra:
  run:
    dir: /home/nibio/mutable-outside-world/data_for_test_results
    
